export const defaultTheme = {
    colorWhite: '#ffffff',
    colorBlackText: '#333333',
    colorBlack: '#000000',
    colorBlackModal: 'rgba(0, 0, 0, 0.6)',
    colorBlackModal30: 'rgba(0, 0, 0, 0.3)',
    colorGrey: '#f6f6f6',
    colorDarkGray: '#6b6b6b',
    colorLightBlue: '#c8e5ff',
    colorBlue: '#add6fb',
    colorDarkBlue: '#56b0ff',
    colorLightGreen: '#aaefa3',
    colorGreen: '#86df7e',
    colorLightRed: '#f75531a7',
    colorRed: '#f75531',
    colorOrange: '#fc9b27',
    colorOrangeHover: '#fc7427',
    fontFamily: '"Montserrat", "Arial", sans-serif',
    fontSizeDefault: "18px",
    lineHeightDefault: "27px",
    fontWeightDefault: '400',
    pageWidth: "1280px",
    pagePadding: "90px",
    indent: "20px",
  }
